integration-server:
  enabled: true
  nameOverride: is
  resources:
    requests:
      memory: 12Gi
    limits:
      memory: 16Gi
  keySecrets:
    name: keystore-is
    mountPath: "/opt/softwareag/common/conf"
  configMapEnvRefs:
    - name: endpoint-db-wm
    - name: endpoint-db-cache
    - name: endpoint-db-cs
    - name: endpoint-db-ewih
    - name: endpoint-db-questionnaire
    - name: endpoint-db-questionnaire-read
    - name: endpoint-um
    - name: endpoint-ip-ldap
    - name: endpoint-db-drs
    - name: endpoint-db-ds
    - name: endpoint-db-ds-read
    - name: endpoint-db-productconfigurator
  secretEnvRefs:
    - name: credentials-is
    - name: credentials-db-wm
    - name: credentials-db-cache
    - name: credentials-db-cs
    - name: credentials-db-ewih
    - name: credentials-db-questionnaire
    - name: credentials-db-questionnaire-read
    - name: credentials-ip-ldap
    - name: credentials-db-drs
    - name: credentials-db-ds
    - name: credentials-db-ds-read
    - name: credentials-db-productconfigurator
  envs:
    - name: DISABLED_PACKAGES
      value: RI_Level_v121,RI_Level_v133,RI_Level_v143,RI_Level_v144,RI_Level_v152,RI_Level_v153
    - name: WS_CONS_EWIHHTTP_HOST
      value: kla-dev-ewih-service
    - name: WS_CONS_EWIHHTTP_PORT
      value: "9081"
    - name: GV_CUSTOMBACKENDS_USEHTTPALIASES
      value: "true"
    - name: MWS_HOST
      value: kla-dev-mws
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "80.95.163.20,149.146.5.85,193.172.150.192/26,91.240.70.5,183.82.112.139,182.73.163.98,34.91.89.124"
      # 80.95.163.20       = guida-office
      # 149.146.5.85       = guida vpn
      # 193.172.150.192/26 = ccs office
      # 91.240.70.5        = 7bulls
      # 183.82.112.139     = comakeit-primary
      # 182.73.163.98      = comakeit-backup
      # 34.91.89.124       = Guida monitoring
    hosts:
      - host: is.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 5555
    tls:
      - hosts:
          - is.kla-dev.dev-1.dip.ccs.nl
        secretName: is-tls