apiVersion: v1
data:
  DB_EWIH_CONN: jdbc:oracle:thin:@20.160.4.245:1521/XE
  DB_EWIH_HOST: 20.160.4.245
  DB_EWIH_INST: XE
  DB_EWIH_PORT: "1521"
  DB_EWIH_SERV: XE
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: endpoint-db-ewih
  namespace: placeholder
