apiVersion: v1
data:
  DB_ATTACHMENT_CONN: jdbc:oracle:thin:@20.160.4.245:1521/XE
  DB_ATTACHMENT_HOST: 20.160.4.245
  DB_ATTACHMENT_INST: XE
  DB_ATTACHMENT_PORT: "1521"
  DB_ATTACHMENT_SERV: XE
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: endpoint-db-attachment
  namespace: placeholder
