apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
namespace: kla-acc
configMapGenerator:
- behavior: merge
  envs:
  - envs/endpoint-db-attachment.properties
  name: endpoint-db-attachment
- behavior: merge
  envs:
  - envs/endpoint-db-cache.properties
  name: endpoint-db-cache
- behavior: merge
  files:
  - files/applications-config.yaml
  name: applications-config
- behavior: merge
  files:
  - files/podinfo-values.yaml
  name: podinfo-values
- behavior: merge
  files:
  - files/test-file-1.tgz
  name: test-file-1
- behavior: merge
  files:
  - files/test-file-2.tgz
  name: test-file-2
